# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=5)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
